name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
    - name: Build site
      run: npm -w=site run build
    - name: Deploy
      run: |
        echo '${{ secrets.SSH_PRIVATE_KEY }}' > github
        chmod 600 ./github
        rsync -e "ssh -i ./github -p 22 -o StrictHostKeyChecking=no" \
          -avz \
          site/dist/ ${{ secrets.DEPLOY_TARGET }}
